@echo off
cd /d "C:\Users\iulii\Desktop\dashboard"
echo Initializing Git repository...
git init
echo Adding remote repository...
git remote add origin https://github.com/weblab420com/medical_website.git
echo Adding all files...
git add .
echo Creating commit...
git commit -m "Update: Expanded accordion view by default - all content blocks visible"
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
